# Generated by Django 4.2.1 on 2023-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Androidapp', '0002_androidapp_userprofile_usertask_delete_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/app_images'),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='link',
            field=models.URLField(default='https://default-link.com'),
        ),
    ]
