# Generated by Django 4.2.1 on 2023-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Androidapp', '0003_androidapp_image_androidapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='category',
            field=models.CharField(choices=[('1', 'Entertainment'), ('2', 'Utility'), ('3', 'Others')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='subcategory',
            field=models.CharField(choices=[('1', 'Social Media'), ('2', 'Media Player'), ('3', 'Gamming')], default='1', max_length=50),
        ),
    ]
